# Generated by Django 2.1.15 on 2020-07-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='page_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='unit',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
