# Generated by Django 2.1.15 on 2020-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0002_auto_20200723_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
