# Generated by Django 2.1.15 on 2020-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0003_auto_20200723_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('city_code', models.CharField(max_length=40)),
                ('city_name', models.CharField(max_length=40)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
