# Generated by Django 2.1.15 on 2020-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0004_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='note',
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(default='启用', max_length=10, null=True),
        ),
    ]
