# Generated by Django 2.1.15 on 2020-07-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0005_auto_20200723_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
