# Generated by Django 2.1.15 on 2020-07-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0006_auto_20200724_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city_code',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='city_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
