# Generated by Django 2.1.15 on 2020-07-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0007_auto_20200724_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_order_tou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20)),
                ('boci', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=40, null=True)),
                ('store_code', models.CharField(max_length=20)),
                ('store_name', models.CharField(max_length=40, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
