# Generated by Django 2.1.15 on 2020-07-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0008_purchase_order_tou'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Del',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20)),
                ('item_code', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=200)),
            ],
        ),
    ]
