# Generated by Django 2.1.15 on 2020-07-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0010_purchase_order_tou_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_del',
            name='boci',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='date',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='item_gg',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='note',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='store_code',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='store_name',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='unit',
            field=models.CharField(default='', max_length=20),
        ),
    ]
