# Generated by Django 2.1.15 on 2020-07-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0011_auto_20200724_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='classification',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
