# Generated by Django 2.1.15 on 2020-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0017_so_first_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_del',
            name='sure_num',
            field=models.IntegerField(default=0),
        ),
    ]
