# Generated by Django 2.1.15 on 2020-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0018_purchase_del_sure_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=40, null=True)),
                ('classification', models.CharField(max_length=40, null=True)),
                ('unit', models.CharField(max_length=40, null=True)),
                ('page_num', models.IntegerField(default=0)),
                ('stock_num', models.IntegerField(default=0)),
                ('update_time', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
