# Generated by Django 2.1.15 on 2020-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0019_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_tou',
            name='sure_status',
            field=models.CharField(default='未确认', max_length=10, null=True),
        ),
    ]
