# Generated by Django 2.1.15 on 2020-07-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0020_purchase_order_tou_sure_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Frozen_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='Incoming_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='Pending_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='Picked_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='Reserved_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='avail_num',
            field=models.IntegerField(default=0),
        ),
    ]
