# Generated by Django 2.1.15 on 2020-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0021_auto_20200728_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='so_first_api',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
