# Generated by Django 2.1.15 on 2020-07-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0024_auto_20200728_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='level',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
