# Generated by Django 2.1.15 on 2020-07-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0025_store_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_del',
            name='note_out',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='order_code_out',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='out_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase_del',
            name='status_out',
            field=models.CharField(default='待下发', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order_tou',
            name='note_out',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order_tou',
            name='order_code_out',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order_tou',
            name='status_out',
            field=models.CharField(default='待下发', max_length=10, null=True),
        ),
    ]
