# Generated by Django 2.1.15 on 2020-07-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0029_auto_20200729_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_order_tou',
            name='pur_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale_del',
            name='pur_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
