# Generated by Django 2.1.15 on 2020-07-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0030_auto_20200729_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
    ]
