# Generated by Django 2.1.15 on 2020-07-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0032_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(default='2', max_length=4, null=True),
        ),
    ]
