# Generated by Django 2.1.15 on 2020-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0034_auto_20200730_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='SALE_First_API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20)),
                ('boci', models.CharField(default='', max_length=20, null=True)),
                ('date', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('detial', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
