# Generated by Django 2.1.15 on 2020-08-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0036_boci'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='pur_min_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='pur_multiple_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='so_min_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='so_multiple_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boci',
            name='status',
            field=models.CharField(default='待下发', max_length=10, null=True),
        ),
    ]
