# Generated by Django 2.1.15 on 2020-08-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunjie', '0037_auto_20200823_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='pur_min_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='pur_multiple_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='so_min_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='so_multiple_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
